<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ankur" name="Default test" tests="9" failures="3" timestamp="5 Mar 2017 13:08:27 GMT" time="116.88" errors="0">
  <testcase name="DemoScreenerTest" time="14.878" classname="com.core.ddf.Indee.testcases.DemoScreener"/>
  <testcase name="DemoScreenerTest" time="21.506" classname="com.core.ddf.Indee.testcases.DemoScreener"/>
  <testcase name="DemoScreenerTest" time="9.808" classname="com.core.ddf.Indee.testcases.DemoScreener"/>
  <testcase name="DemoScreenerTest" time="16.088" classname="com.core.ddf.Indee.testcases.DemoScreener">
    <failure type="java.lang.AssertionError" message="views count does not exist">
      <![CDATA[java.lang.AssertionError: views count does not exist
	at org.testng.Assert.fail(Assert.java:94)
	at com.core.ddf.Indee.base.BaseTest.reportFailure(BaseTest.java:168)
	at com.core.ddf.Indee.base.BaseTest.demoScreener(BaseTest.java:233)
	at com.core.ddf.Indee.testcases.DemoScreener.DemoScreenerTest(DemoScreener.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- DemoScreenerTest -->
  <testcase name="DemoScreenerTest" time="11.755" classname="com.core.ddf.Indee.testcases.DemoScreener">
    <failure type="java.lang.AssertionError" message="PerishesIn does not exist">
      <![CDATA[java.lang.AssertionError: PerishesIn does not exist
	at org.testng.Assert.fail(Assert.java:94)
	at com.core.ddf.Indee.base.BaseTest.reportFailure(BaseTest.java:168)
	at com.core.ddf.Indee.base.BaseTest.demoScreener(BaseTest.java:248)
	at com.core.ddf.Indee.testcases.DemoScreener.DemoScreenerTest(DemoScreener.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- DemoScreenerTest -->
  <testcase name="DemoScreenerTest" time="11.487" classname="com.core.ddf.Indee.testcases.DemoScreener">
    <failure type="java.lang.AssertionError" message="PerishesIn does not exist">
      <![CDATA[java.lang.AssertionError: PerishesIn does not exist
	at org.testng.Assert.fail(Assert.java:94)
	at com.core.ddf.Indee.base.BaseTest.reportFailure(BaseTest.java:168)
	at com.core.ddf.Indee.base.BaseTest.demoScreener(BaseTest.java:248)
	at com.core.ddf.Indee.testcases.DemoScreener.DemoScreenerTest(DemoScreener.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- DemoScreenerTest -->
  <testcase name="DemoScreenerTest" time="14.352" classname="com.core.ddf.Indee.testcases.DemoScreener"/>
  <testcase name="DemoScreenerTest" time="12.191" classname="com.core.ddf.Indee.testcases.DemoScreener"/>
  <testcase name="DemoScreenerTest" time="0.001" classname="com.core.ddf.Indee.testcases.DemoScreener">
    <skipped/>
  </testcase> <!-- DemoScreenerTest -->
</testsuite> <!-- Default test -->
